// VS Code theme scopes do not correspond to Monaco Monarch token names.
// Bridge the tokens emitted by Monaco, including embedded Vue code, to Dark 2026.
export const monarchTokenRules = [
  { token: 'keyword', foreground: 'C586C0' },
  { token: 'identifier', foreground: 'BBBEBF' },
  { token: 'type.identifier', foreground: '4EC9B0' },
  { token: 'tag', foreground: '6ECF80' },
  { token: 'attribute.name', foreground: '9CDCFE' },
  { token: 'attribute.value', foreground: 'A5D6FF' },
  { token: 'key', foreground: '9CDCFE' },
  { token: 'regexp', foreground: 'D16969' },
  { token: 'number', foreground: 'B5CEA8' },
  { token: 'string', foreground: 'A5D6FF' },
  { token: 'comment', foreground: '8B949E' },
  { token: 'constant', foreground: '79C0FF' },
  { token: 'function', foreground: 'D2A8FF' },
  { token: 'variable', foreground: '79C0FF' },
  { token: 'namespace', foreground: '4EC9B0' },
  { token: 'keyword.declaration.js', foreground: 'FF7B72' },
  { token: 'keyword.declaration.ts', foreground: 'FF7B72' },
  { token: 'keyword.import.js', foreground: 'C586C0' },
  { token: 'keyword.import.ts', foreground: 'C586C0' },
  { token: 'keyword.import.python', foreground: 'C586C0' },
  { token: 'keyword.declaration.python', foreground: 'C586C0' },
  { token: 'type.python', foreground: '4EC9B0' },
  { token: 'tag.css', foreground: 'D7BA7D' },
  { token: 'tag.vue', foreground: '6ECF80' },
  { token: 'attribute.name.vue', foreground: '9CDCFE' },
  { token: 'string.vue', foreground: 'A5D6FF' },
  { token: 'delimiter.vue', foreground: 'BBBEBF' },
]
